import React from 'react'

export default function PrivacyPolicy({ onNavigate, onDeleteAccount, isAuthenticated }) {
  return (
    <div className="min-h-screen bg-slate-950 text-white px-4 py-12 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-5xl rounded-[2rem] border border-white/10 bg-slate-900/95 p-8 shadow-[0_30px_100px_-40px_rgba(15,23,42,0.8)] backdrop-blur-xl sm:p-10">
        <div className="flex flex-col gap-6">
          <div>
            <p className="text-sm uppercase tracking-[0.24em] text-cyan-300/90">Privacy policy</p>
            <h1 className="mt-3 text-4xl font-extrabold tracking-tight text-white sm:text-5xl">
              Your privacy and data rights
            </h1>
          </div>

          <section className="space-y-4 rounded-[1.5rem] border border-white/10 bg-white/5 p-6">
            <h2 className="text-2xl font-semibold text-white">What we collect</h2>
            <p className="text-sm leading-7 text-slate-300">
              Threadwise stores only the information required for your account: your email address and a hashed password.
              This data is stored locally in your browser using <span className="font-semibold text-white">localStorage</span>.
            </p>
          </section>

          <section className="space-y-4 rounded-[1.5rem] border border-white/10 bg-white/5 p-6">
            <h2 className="text-2xl font-semibold text-white">How we use your data</h2>
            <p className="text-sm leading-7 text-slate-300">
              Your data is used only to authenticate your account and keep your settings in this browser. We do not sell or share your information.
            </p>
            <p className="text-sm leading-7 text-slate-300">
              Any password reset information is generated by the app and, when available, sent through your configured email provider.
            </p>
          </section>

          <section className="space-y-4 rounded-[1.5rem] border border-white/10 bg-white/5 p-6">
            <h2 className="text-2xl font-semibold text-white">Your rights</h2>
            <ul className="list-disc space-y-2 pl-5 text-sm leading-7 text-slate-300">
              <li>You can withdraw consent and delete your account data any time.</li>
              <li>Because data is stored locally, deleting account data removes it from this browser.</li>
              <li>If you use a different browser or device, your account will not carry over unless you register again.</li>
            </ul>
          </section>

          <section className="space-y-4 rounded-[1.5rem] border border-white/10 bg-white/5 p-6">
            <h2 className="text-2xl font-semibold text-white">How to delete your data</h2>
            <p className="text-sm leading-7 text-slate-300">
              Click the button below to erase your Threadwise account data from this browser and sign out immediately.
            </p>
            {isAuthenticated ? (
              <button
                type="button"
                onClick={onDeleteAccount}
                className="rounded-full bg-rose-500 px-6 py-3 text-sm font-semibold text-white transition hover:bg-rose-400"
              >
                Delete my account data
              </button>
            ) : (
              <p className="text-sm text-slate-400">Sign in to delete your account data from this browser.</p>
            )}
          </section>

          <div className="flex flex-wrap gap-4 pt-4">
            <button
              type="button"
              onClick={() => onNavigate('home')}
              className="rounded-full border border-slate-700 bg-slate-950 px-6 py-3 text-sm font-semibold text-white transition hover:bg-slate-800"
            >
              Back to home
            </button>
            <button
              type="button"
              onClick={() => onNavigate('login')}
              className="rounded-full bg-cyan-500 px-6 py-3 text-sm font-semibold text-white transition hover:bg-cyan-400"
            >
              Go to login
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
